### ISSUE TITLE
Masthead in product page layout not contained within a landmark

### ISSUE THREAD

**Issue by keithkennedyHO** [x-govuk/govuk-eleventy-plugin#169]
Within the product layout, the masthead component `xGovukMasthead` is not contained within a landmark.

Within our project, this is triggering [this automated accessibility check](https://dequeuniversity.com/rules/axe/4.6/region).

# Proposal

I believe both the masthead and the content should both be contained within a [main landmark](https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/main.html). Currently, on the product layout, only the content is contained within the main landmark.

**Comment by keithkennedyHO** [comment]
PR #170 raised as potential fix.

**Comment by paulrobertlloyd** [comment]
Turns out also that, by not having the masthead component within the `<main>` containing element, the layout breaks on Firefox and Chrome on Windows, and Chrome on Android:

![image](https://github.com/x-govuk/govuk-eleventy-plugin/assets/813383/de0479e0-7218-4c33-bbae-c62afa5edff6)

Without upstream changes to `govuk-template`, will need to find another way to allow the masthead to be inserted into the layout within the `<main>` containing element.
