### ISSUE TITLE
Adding cookie banner

### ISSUE THREAD

**Issue by nnagewad** [x-govuk/govuk-eleventy-plugin#315]
Just wondering if it's possible to add a cookie banner?

If so, are there any additional settings that need to be setup?

**Comment by paulrobertlloyd** [comment]
To add a cookie banner (or add items to the head, with regards to #314), you’d need to create your own layouts (which can then extend from those provided by the plugin).

You can see an example of this in the layouts used for the Design History template repo (e.g. https://github.com/x-govuk/govuk-design-history-template/blob/main/app/_layouts/page.njk).

Layouts are a bit of hack right now, and this situation should improve with #290. But even with the addition of virtual templates, I think you’d still need to create your own layouts once you move off the beaten path of those provided by the plugin.

**Comment by nnagewad** [comment]
Right on. Thank you for your help @paulrobertlloyd 👍🏽

**Comment by paulrobertlloyd** [comment]
Feel free to reopen this issue or create another one if you have any further questions.

**Comment by joelanman** [comment]
just wondering if this could be reopened and considered as a feature of the plugin? Just thinking that it's probably a common need if people use Google Analytics. I'm new to the plugin so feel free to say if this is just not in the remit/intended purpose

**Comment by paulrobertlloyd** [comment]
Maybe but – and currently a little sleep deprived so feeling a little bit grumpy and unreasonable – don’t have analytics! Somewhat of the mind if you want to add Google Analytics or anything needing cookies, you should do the leg work. As I say, am grumpy, and this topic presses my buttons!

Also, at some point, the plugin needs to draw a line in the sand. As I say, things should helpfully get a bit easier in the next major version in that layouts should hopefully be easier to override or extend, so that’d be the escape hatch for such additions.

**Comment by joelanman** [comment]
thats cool, but as you're aware, sometimes the decision to use analytics and which one is made by other people

**Comment by paulrobertlloyd** [comment]
Don't I know it 😔

Not entirely opposed to the idea, but it's not a priority right now.

**Comment by paulrobertlloyd** [comment]
…always open to PRs, of course 😉
